Resolve outstanding dictionary issues within the SCI repo
Green-Software-Foundation/Dictionary pull request #2
Opened 2021-08-19 17:30 UTC by Sealjay

Adds to green-software-foundation/software-carbon-intensity#32, resolves green-software-foundation/software-carbon-intensity#19 and resolves green-software-foundation/software-carbon-intensity#29 - @atg-abhishek

2021-08-29 13:25 UTC, atg-abhishek commented
Yes this gets merged on the call - did it not come up on the agenda in this week's call? I had it written in on the agenda but maybe there wasn't enough time and we didn't get to it? cc @seanmcilroy29 @Henry-WattTime

2021-08-31 08:28 UTC, Sealjay commented
Yeah I think it's related to #64 - there's so much going on, it's hard to get to everything on the calls :)

2021-09-02 13:31 UTC, SaraEmilyBergman commented on Dictionary/Dictionary.md
> +	<td><strong>Ability to Act</strong></td>
Nitpicking here, but don't we want "Ability to Act" below "Agent" and "Action" as both of those are used in the definition?

2021-09-02 14:50 UTC, Sealjay commented on Dictionary/Dictionary.md
> +	<td><strong>Ability to Act</strong></td>
Ah we do, yes! When we merge #24, which changes the table format to .MD with @atg-abhishek @TaylorPrewitt, I'll reorder @SaraEmilyBergman  - good catch

2021-09-02 15:50 UTC, atg-abhishek commented
We want to keep it in alphabetical order since it is a dictionary and maybe add in internal references to existing terms.

2021-09-02 15:57 UTC, Sealjay commented
@atg-abhishek agreed - definitely in alphabetical order, was just waiting for the markdown changes to be merged before I fixed, otherwise it would conflict further

2021-09-02 16:16 UTC, Sealjay commented
@atg-abhishek - fixed, and ready to merge. mildly painful!

2021-09-03 02:36 UTC, atg-abhishek requested changes
Thanks for working on this @Sealjay - I noticed that the `md` table hasn't rendered correctly, could you take a look at that? Otherwise, this is good to go!

2021-09-16 16:08 UTC, Sealjay reviewed
The MD should now render correctly

2022-01-21 14:40 UTC, atg-abhishek commented
@Sealjay can you resolve the conflicts and we can move to merge this? Thanks!

2022-01-21 15:40 UTC, Sealjay commented
> @Sealjay can you resolve the conflicts and we can move to merge this? Thanks!

should be done now @atg-abhishek and @seanmcilroy29 - had to merge in the two other PRs :)

2022-03-14 09:55 UTC, Sealjay commented
hey @atg-abhishek and @seanmcilroy29 - just bumping this one, thanks :)

2022-03-14 15:48 UTC, atg-abhishek approved these changes
LGTM!

2022-03-14 15:50 UTC, Sealjay commented
Awesome thanks- is someone with permissions able to merge? @atg-abhishek @seanmcilroy29

2022-03-14 15:52 UTC, atg-abhishek commented
I've added it to the agenda for the meeting for review before it can be merged in as per the WoW of the WG :)

2022-03-14 16:01 UTC, Sealjay commented
ok, sure - I thought we discussed this in August and September. This is pulling in upstream changes only, no new content.
https://github.com/Green-Software-Foundation/standards_wg/blob/4542e07030082974781aa268df7e9113dd120e90/Agenda_Minutes/2021.09.30_Agenda.md

2022-03-17 16:41 UTC, merged